# .scrutinizer.yml
tools:
    external_code_coverage:
        runs: 28

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
    paths: {  }
