# .scrutinizer.yml
tools:
    external_code_coverage: true
    # runs: 28    # Scrutinizer will wait for two code coverage submissions

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
    paths: {  }
