language: php

sudo: false

services:
  - redis-server
  - memcached
  - mongodb

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm
  - hhvm-nightly

env:
  - DB=apc
  - DB=redis
  - DB=mongodb
  - DB=sqlite
  - DB=mysql
  - DB=pgsql
  - DB=memcached

install:
  - travis_retry composer self-update
  - travis_retry composer install -o --no-interaction --prefer-source
  - mkdir -p build/logs
  - tests/bin/travis-init.sh

before_script:
  # xdebug is not installed on HHVM and PHP 7, so skip code coverage (COVERAGE="no").
  - if [[ $TRAVIS_PHP_VERSION != '7.0' || $TRAVIS_PHP_VERSION != 'hhvm' ]]; then COVERAGE="no"; fi

script:
  - if [ "$COVERAGE" != "no" ]; then vendor/bin/phpunit --colors --verbose --coverage-text --coverage-clover build/logs/clover.xml; fi
  - if [ "$COVERAGE" == "no" ]; then vendor/bin/phpunit --colors --verbose; fi

after_script:
  - if [ "$COVERAGE" != "no" ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
  - php vendor/bin/coveralls -v

notifications:
  irc: "irc.freenode.org#ouarz"
  email:
    recipients:
      - dev-team@ouarz.net
    on_success: change
    on_failure: change

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.3
      env: DB=memcached   # memcached does not working properly on PHP 5.3
    - php: hhvm
    - php: hhvm-nightly
    - php: nightly
